---
title: Nodyn atgoffa gwirion
hero_image: images/banner.png
description: Gadewch i'ch micro:bit eich atgoffa i lacio a gwneud ystum
version: 4
listed: true
copyedit: true
last_tested: "2023-08-11"
steps:
  - title: Gosod nodyn atgoffa
