title: Recordatorio
hero_image: images/banner.png
description: Deja que tu micro:bit te recuerde que debes relajarte y adoptar una pose
version: 4
listed: true
copyedit: true
last_tested: "2023-08-11"
steps:
  - 
    title: Establece un recordatorio
