title: Silly reminder
hero_image: images/banner.png
description: Άσε το micro:bit να σου υπενθυμίσει να χαλαρώσεις και να κάνεις μια στάση
version: 4
listed: false
copyedit: false
last_tested: "2023-08-11"
steps:
  - 
    title: Ορισμός υπενθύμισης
